### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by FrankHold** [cyrusadkisson/etheria#2]
Suggestions for 1.XX (you means the player)

Economy     - you can send a block to another land tile (payment solved in a different contract)
Progression - you can create only blocks with the colour number of blocks you have 
                      or the colour number above the current colour number
Function    - you can create a contract in which a action is defined
                  - as example - move a block to another location (open a door)
                  - Everyone can call the contract (and pay 0.001 or 1000 Ether for it)
                  - Would require registering a contract which has access to your land tile
Delete       - because the limitation of total number of blocks - a block should be erasable

Tetris      - If a block would have only the horizontal (x and y) coordinates 
                 it could fall Tetris like to the ground and stop when it hits another block
               - it would simplify building (and the check routine isValidLocation)
               - would require to be able to change the order of blocks

Reminds me on "clashes of clans" or "farmville" 
- Block 18  - a tractor
- Block 19  - a pig
- Block 20  - a cat
- ...

**Comment by FrankHold** [comment]
Sorry changed my mind. 

Ethereia should (in my mind) be as featureless as ethereum itself. You (the player) should be able to do anything with it and not to be just a game. If you register your patch of land to a “farmville” contract you play farmville and if you register your patch of land to a "clashes of clans" contract you play "clashes of clans" … or “Tic-tac-toe”. Etheria shows only the state of the contract. Player A moved chess peace “King” to A3 etheria.editBlock.sendTransaction(16,5,27,[0,1,-42,0,-14],{from:"ThisRegisteredContract",gas:2000000,value:0}). Or someone just builds a small house in the wood.

**Comment by fivedogit** [comment]
Yeah I agree with the "you can do anything you want" sentiment, but as I
built Etheria, I realized that Ethereum is probably not well suited to
building virtual worlds. There's simply too much information to store
and process for it to be viable. After placing only 30 blocks, it runs
above the gas limit because it has to check each 3D hex for conflicts.

I think Etheria was a fun experiment, but unless there is some
technological change that allows for more efficient information storage,
it's hard to see how it moves beyond what it is right now.

And very cool log cabin, btw. I smiled huge when I saw it. Thanks for
giving Etheria a try!

Cyrus

On Tue, Nov 3, 2015, at 06:09 AM, Frank Hold wrote:
> Sorry changed my mind.


> Ethereia should (in my mind) be as featureless as ethereum itself. You
> (the player) should be able to do anything with it and not to be just
> a game. If you register your patch of land to a “farmville” contract
> you play farmville and if you register your patch of land to a
> "clashes of clans" contract you play "clashes of clans" … or “Tic-tac-
> toe”. Etheria shows only the state of the contract. Player A moved
> chess peace “King” to A3 etheria.editBlock.sendTransaction(16,5,27,[0,1,-42,0,-
> 14],{from:"ThisRegisteredContract",gas:2000000,value:0}). Or someone
> just builds a small house in the wood.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/fivedogit/etheria/issues/2#issuecomment-153316587

**Comment by FrankHold** [comment]
Thank you for your replay!
No question the technical challenges are huge but I enjoy the project especially because I can show someone something ‘real’ who has never heard of ethereum before.

**Comment by cyrusadkisson** [comment]
Hey Frank, your cabin is back online as of today. https://etheria.world/explorer.html

Technically it was always there, obviously. I just decided to bring the website back.

**Comment by cyrusadkisson** [comment]
Hi Frank. Etheria sold out on both v1.2 "official" and the previous v1.1 maps because they were the first NFTs. Your cabin is likely the first-ever UGC on the blockchain and is likely very valuable. Would you contact me on twitter? username "etheria_feed"
