### ISSUE TITLE
ETH sent via SetOwner command

### ISSUE THREAD

**Issue by Westophalopalis** [cyrusadkisson/etheria#3]
I'm dumb and accidently sent 2 ETH via the OwnerSet command to Etherias contract on 13MAR2021. Any chance the ETH can be sent back, or is it locked in there perminately. I can send you the addresses used if needed.

**Comment by cyrusadkisson** [comment]
Well I was prepared to tell you bad news that your ETH is gone forever, BUT it looks like there may be hope. Scanning the contract code I see:

```
 function empty() 
   {
	   creator.send(address(this).balance); // etheria should never hold a balance. But in case it does, at least provide a way to retrieve them.
   }
```
If I remember correctly (it's been > 5 years), I can use this function to empty the contract of any stuck ether into my own account which I can then manually send wherever. HOWEVER, I'm having issues getting the blockchain to sync for me locally and haven't been able to interact with the contract myself yet. I know it's possible. It's just a geth/hardware thing.

Send me your transaction ID and when I'm able to interact with the contract I'll attempt to drain the stuck funds and return them. 

This may be some days or weeks, though. And there's no guarantee this will work. But it's worth a shot.

**Comment by Westophalopalis** [comment]
Thank Cyrus,

I understand that a lot of all this came out of nowhere after years of
inactivity.  Honestly there is no rush, or even guarantee that it will
work, and much of this is the nature of the beast.  I attached my two
transaction hashes bellow:

0xf35dc5230be2cd1bf0a67198202a4f287fa24c832ae0d3ae727d0c314abbcf0b
https://etherscan.io/tx/0xf35dc5230be2cd1bf0a67198202a4f287fa24c832ae0d3ae727d0c314abbcf0b

0x58b3c622d689e710f4fca81e2c0d9b4dafa88ef640d34afa3cb11a6d58f39690
https://etherscan.io/tx/0x58b3c622d689e710f4fca81e2c0d9b4dafa88ef640d34afa3cb11a6d58f39690

Thank you for your help.  Please do not stress over this, I understand how
much all of this is coming out of nowhere for a 5 year old project.  Have a
great day.
Cheers,
-Wes

**Comment by bakkuu** [comment]
Hello Cyrus,

I got kind of the same issue here.
I tried to buy a tile which was already owned by someone else (what a dumbass i am), as a result my ETH is stuck in the contract.

I know this is completely my fault, but just in case there is in deed a possibility to retrieve my loss, here is my transaction hash : 

0x116d4af5134e5bc0f7addcf1d8dce0f670f5551c87428169eb9aec18d21ae8c4
https://etherscan.io/tx/0x116d4af5134e5bc0f7addcf1d8dce0f670f5551c87428169eb9aec18d21ae8c4

Thanks a lot for your help,
- Bakkuu
